apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
  namespace: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: us-east1-docker.pkg.dev/linkedlens-452503/linkedlens-repo/open-webui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        # - name: OLLAMA_BASE_URL
        #   value: "http://ollama-service.open-webui.svc.cluster.local:11434"
        - name: SCARF_NO_ANALYTICS
          value: "true"
        - name: DO_NOT_TRACK
          value: "true"
        - name: ANONYMIZED_TELEMETRY
          value: "false"
        - name: GOOGLE_PROJECT_ID
          value: linkedlens
        - name: DB_NAME
          value: "linked-lens"
        - name: DATABASE_URL
          value: 'postgresql://openwebui:openwebui@34.145.134.181:5432/openwebui'
        - name: ENABLE_OAUTH_SIGNUP
          value: "false"
        - name: GOOGLE_CLIENT_ID
          value: ""
        - name: GOOGLE_CLIENT_SECRET
          value: ""
        - name: GOOGLE_REDIRECT_URI
          value: 'http://linkedlens.duckdns.org/oauth/google/callback'
        tty: true
        volumeMounts:
        - name: webui-volume
          mountPath: /app/backend/data
      volumes:
      - name: webui-volume
        persistentVolumeClaim:
          claimName: open-webui-pvc          