name: Setup, Build, Deploy

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'model-development/src/**'
  #     - '.github/workflows/deploy-to-gke.yml'
  workflow_dispatch:

jobs:
  setup-build-deploy-push:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Setup, Build, Publish, and Deploy Model
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      
      - id: 'test-vars'
        run: echo "Cluster name is ${{ vars.GKE_CLUSTER_NAME }}"  

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'linkedlens-cluster'
          location: ${{ vars.GCP_REGION }}
      
      - id: 'get-pods'
        run: 'kubectl get pods'

      - name: 'Setup Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud cli'
        run: 'gcloud info'
      
      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker us-east1-docker.pkg.dev
      
      - name: Build image
        run: |-
          docker build . --file ./Dockerfile --tag us-east1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/linkedlens-repo/open-webui:latest
      
      - name: Docker push
        run: |-
          docker push us-east1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/linkedlens-repo/open-webui:latest
      
      - name: Deploy
        run: |-
          kubectl apply -f deployment.yaml --namespace app && \
          kubectl rollout status deployment/model-dev-deployment -n app && \
          kubectl apply -f ./kubernetes/service.yaml --namespace app

      - name: Restart deployment
        run: kubectl rollout restart deployment model-dev-deployment -n app